### ISSUE TITLE
Empty table on input causes error

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/r-custom-application-tree#1]
Viz. job `331525087`:  Cannot upload file 'linked_orders.csv' to table 'out.c-app-snowflake.order_tree' in Storage API: Some columns are missing in the csv file. Missing columns: levels,root. Expected columns: parent,child,levels,root. Please check if the expected delimiter "," is used in the csv file.
`ExceptionId docker-7c03753be01959c5b0d8aa4d67a5d8f6`

**Comment by odinuv** [comment]
fixed in 4a6c7c642998439507636a8b2466b23910c00c5a
