### ISSUE TITLE
The test is a lie

### ISSUE THREAD

**Issue by odinuv** [keboola/r-custom-application-tree#5]
https://github.com/keboola/app-tree/pull/4

**Comment by kacurez** [comment]
testovacie data prezentuju invalidny vstup. Navrhujem takyto vstup osetrit tym ze to skonci chybou s hlaskou "no roots found" + sa pripadne prida hlaska ze niektore nody niesu zaevidovane(tie ktore su v parents stlpci ale nikde niesu v child stlpci)

**Comment by odinuv** [comment]
reprezentuji validni vstup, protoze to tak odjakziva bylo:
https://github.com/keboola/app-tree/blob/1.0.2/tests/data/02/in/tables/tree.csv
https://github.com/keboola/app-tree/blob/1.0.2/tests/data/03/in/tables/tree.csv
https://github.com/keboola/app-tree/blob/1.0.2/tests/testthat/testApplication.R#L18
ostatne i dnes to tak v testech je, akorat se ty testy neprovadi

je to hlavne proto, ze kdybysme rekli, ze neexistujici koren = chyba, tak se objevi skupina podivnych problemu s "prazdnymi' koreny typu: ` `, `0`, `NULL`, `'NULL'` apod.

**Comment by kacurez** [comment]
ja som cely cas pocital stym ze child ktoreho parent je prave ` ` alebo `0` sa automaticky povazuje za koren stromu(https://keboola.slack.com/archives/C0377LNRH/p1513001135000375) takze koren sa nijak zvlast nedopocitava.

pre children ktore maju hodnoty ` ` alebo `0` sa ich child->parent nikde nezohladni, to by mohlo byt tiez osetrene hlaskou/chybou.

Ja by som bol radsej aby sa takymito chybovymi hlaskami zaviedli mantinely na ktore je uzivatel upozorneny pocas konfigurovania app tree, takze si potom podla toho prisposobi vstupne data transformaciou, co sa vlastne deje uz teraz.

**Comment by odinuv** [comment]
no ale ten test jsi tam nechal https://github.com/keboola/app-tree/blob/master/tests/data/03/in/tables/tree.csv :)

problem je v tom, ze to zadny chybovy hlasky nepise a nemas to jak udelat (dopredu to nemas sanci zjistit vubec, expost trosku). Tzn. v prvni rade to musi **vzdycky** vracet stejnej pocet radku jaky do toho vlezl, pokud je tam nevalidni root tak to muze:
- bud ho to dopocitat (cili chovat se podle tech soucasnych testu https://github.com/keboola/app-tree/blob/master/tests/data/03/in/tables/tree.csv)
- nebo skoncit cely chybou (s oznacenim pokud mozno vsech nevalidnich rootu)
- nebo vratit radek s prazdnymi hodnotami

V kazdym pripade, ale pokud to neco vrati, tak stejnou tabulku jako byla na vstupu - ty chybejici radky nikdy nikdo nepochopi. A napsat do popisu aplikace, ze root musi byt tak a tak je nanic, protoze uzivatel vubec nemusi vedet, co mu tam prileze za data.

**Comment by kacurez** [comment]
ten test som tam nechal lebo bol zeleny :)

Berem argument ze uzivatel nevie co ma za data a je lepsie mu to nekomplikovat. Pokusil som sa to upravit tak aby tie rooty automaticky dopocitaval, tj neni potreba specifikovat root ze je to child ktoreho parent je ` ` alebo `0`. Trocha sa tym dvihne pamat ale asymptoticka pamatova zlozitost ostava linearna. Testy su samozrejme opat zelene :)

PR - https://github.com/keboola/app-tree/pull/4

**Comment by odinuv** [comment]
fixed in 4b35f3828ea69affa8f7bd7c6f4789ee05d68758
